---
title: "AQS"
author: "Antonio Avila"
date: "10/18/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(RAQSAPI)
library(keyring)
library(beepr)
library(usmap)
library(lubridate)
library(forecast)
library(plotly)
library(rjson)
```

## R Markdown

```{r enable AQS credentials, include = FALSE}
# key_set(service = 'AQSDatamart', username = 'aavila2802@gmail.com')

datamart_user <-  'aavila2802@gmail.com'
server <-  'AQSDatamart'
aqs_credentials(username = datamart_user, key_get(service = server, username = datamart_user))
```

```{r state codes, include = FALSE}

state_codes <- aqs_states()

```


```{r extract ozone data, include = FALSE}

# parameter 62104 is the max temp in a 24 Hr period
# parameter 62105 is the min temp in a 24 Hr period
# parameter 62106 is the temp diff in a 24 Hr period
# parameter 44201 is the ozone 
# parameter 42102 is carbon dioxide

# Working for the parameter code 45201 (benzine) but not for any other codes from the list above

# start_time = proc.time()
# ozone_texas <- aqs_sampledata_by_state(parameter = "44201",
#                                            bdate = as.Date("20200901",
#                                                            format="%Y%m%d"
#                                                            ),
#                                            edate = as.Date("20210901",
#                                                           format = "%Y%m%d"),
#                                            stateFIPS = "48"
#                                           )
# print("Time to Execute:")
# print(proc.time() - start_time)
# beep()

```



```{r import data and combine}

# ozone_texas_20_21 <- read_csv("ozone_texas_20_21.csv")
# ozone_texas_19_20 <- read_csv("ozone_texas_19_20.csv")
# ozone_texas_18_19 <- read_csv("ozone_texas_18_19.csv")
# ozone_texas_17_18 <- read_csv("ozone_texas_17_18.csv")
# 
# ozone_texas <- union(union(union(ozone_texas_17_18, ozone_texas_18_19), ozone_texas_19_20), ozone_texas_20_21)
# 
# write_csv(ozone_texas, "ozone_texas.csv")

ozone_texas <- read_csv("ozone_texas.csv")
ozone_texas["fips"] <- as.integer(ozone_texas$state_code) * 1000 + as.integer(ozone_texas$county_code)

```


```{r function for 8 hour ozone avg}


avg_8hr <- function(data){
  avgs = matrix(nrow = 24-8, ncol = 1)
  for(i in 1:(24-8)) { 
    avgs[i] = mean(data[i:(i+7)], na.rm = TRUE)
  }
  return(avgs)
}


max_8hr_avg <- function(data){
  max_avg = max(avg_8hr(data)) * 1000
  max_avg = trunc(max_avg)
  return(max_avg)
}


```

```{r verify with published data}
# Verified calculations with results from various days published by the Texas Commission on Environmental Quality

test_day <- ozone_texas %>% filter(date_local == "2019-10-02", site_number == "0416")
test_day$sample_measurement %>% max_8hr_avg()

```

```{r find max per county}
daily_max_sites <- ozone_texas %>% 
  group_by(county, fips, site_number, date_local) %>% 
  summarize(max_8hr_avg = max_8hr_avg(sample_measurement))

daily_max_counties <- daily_max_sites %>%
  group_by(county, fips, date_local) %>% 
  summarise(county_max = max(max_8hr_avg, na.rm = TRUE))
```



```{r Harris county ozone lvl}

daily_max_counties %>% filter(county == "Harris") %>% 
  ggplot(aes(date_local, county_max, color = county_max)) + 
    geom_line() + 
    scale_fill_gradient(low = "green", high = "red") +
    geom_hline(yintercept = 70, color = "red") +
    geom_smooth() + 
    ggtitle("Harris County Ozone levels 2017-2021") +
    xlab("Date") +
    ylab("Ozone 8-Hr Max (ppb)")


```




```{r}

daily_max_counties %>% filter(date_local == "2020-05-01") %>% 
  plot_usmap(regions = "counties", include = "TX", data = ., values = "county_max") +
    scale_fill_gradient(low = "green", high = "red", labels = "high", breaks = 70)


daily_max_counties %>% filter(date_local == "2018-05-01") %>% 
  plot_usmap(regions = "counties", include = "TX", data = ., values = "county_max") +
    scale_fill_gradient(low = "green", high = "red")
```




```{r testing plotly map, include = FALSE}
#broken mess around with at some point to compare to regular ggplot

url <- 'https://raw.githubusercontent.com/plotly/datasets/master/geojson-counties-fips.json'
counties <- rjson::fromJSON(file=url)


geo <-  list(
  visible = FALSE, resolution = 110,
  scope = 'usa', 
  showcountries = TRUE, 
  projection = list(type = 'albers usa'),
  countrycolor = toRGB("Black"),
  showlakes = TRUE,
  lakecolor = toRGB("white"),
  showsubunits = T,
  subunitcolor = toRGB("Blue"),
  showland = TRUE,
  landcolor = toRGB("#e5ecf6")
 )

fig <- plot_ly(type = "scattergeo", mode = "markers")

fig <- fig %>% add_trace(geojson = counties, locations = daily_max_counties$fips, 
                          z = daily_max_counties$county_max, type = "choropleth", 
                         marker=list(line=list(width=0), zmin = 0, zmax = 100)
)

fig <- fig %>% layout(geo = geo)
fig

```


























